// <auto-generated />
namespace SePantry_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class barcodefield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(barcodefield));
        
        string IMigrationMetadata.Id
        {
            get { return "201411251939179_barcode-field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
